services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    ports:
      - 5433:5432
  backend:
    build: ./server
    ports:
      - 13000:13000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  frontend:
    build: .
    ports:
      - 4200:4200