###
GET http://localhost:13000/setup

###
GET http://localhost:13000

###
POST http://localhost:13000
Content-Type: application/json

{
    "name": "testLoan1",
    "user_id": 1,
    "principal": 124000,
    "rate": 2.99,
    "termYears": 26,
    "monthlyPayment": null,
    "extraMonthlyPayment": null
}

###
DELETE http://localhost:13000/loans/1
Content-Type: application/json

###
POST http://localhost:13000/users
Content-Type: application/json

{
    "username": "testuser",
    "password": "password"
}

###
GET http://localhost:13000/users

###
DELETE http://localhost:13000/users/1
Content-Type: application/json